application: tbatv-dev
version: 1
runtime: python
api_version: 1

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py
- url: /tasks/.*
  script: cron_main.py
- url: /admin/.*
  script: admin_main.py
  login: required
- url: .*
  script: main.py
  
admin_console:
  pages:
  - name: Appstats
    url: /stats