application: tbatv-dev
version: 1
runtime: python
api_version: 1

builtins:
- appstats: on
- remote_api: on

handlers:
- url: /css
  static_dir: css
- url: /images
  static_dir: images
- url: /tasks/.*
  script: cron_main.py
- url: /admin/.*
  script: admin_main.py
  login: required
- url: .*
  script: main.py

